language: go


go:
  - 1.7.x
  - 1.8.x

before_script:
  - go get -t -v github.com/alex023/httpcli/...

script:
  - go test -v github.com/alex023/httpcli/

notifications:
  email:
    recipients: 12242284@qq.com
    on_success: change
    on_failure: always